# Copyright (c) 2020. TIBCO Software Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.

ARG JAVA_BASE_IMAGE=openjdk:11-slim
FROM ${JAVA_BASE_IMAGE}

ARG POSTGRES_JDBC_DRIVER_VERSION
ARG JASPERREPORTS_SERVER_VERSION
ARG EXPLODED_INSTALLER_DIRECTORY

ENV POSTGRES_JDBC_DRIVER_VERSION ${POSTGRES_JDBC_DRIVER_VERSION:-42.3.1}
ENV JASPERREPORTS_SERVER_VERSION ${JASPERREPORTS_SERVER_VERSION:-8.0.0}
ENV EXPLODED_INSTALLER_DIRECTORY ${EXPLODED_INSTALLER_DIRECTORY:-resources/jasperreports-server-cp-$JASPERREPORTS_SERVER_VERSION-bin}

ENV JRS_HOME /usr/src/jasperreports-server

# Ant
COPY ${EXPLODED_INSTALLER_DIRECTORY}/apache-ant ${JRS_HOME}/apache-ant/

# js-ant script, Ant XMLs and supporting resources in bin
COPY ${EXPLODED_INSTALLER_DIRECTORY}/buildomatic ${JRS_HOME}/buildomatic/

COPY scripts /

RUN chmod +x /*.sh && \
    /installPackagesForJasperserver-ce-cmdline.sh && \
    echo "finished installing packages" && \
    cp -R /buildomatic ${JRS_HOME}/buildomatic && \
    rm /installPackagesForJasperserver*.sh && rm -rf /buildomatic && \
    chmod +x ${JRS_HOME}/buildomatic/js-* && \
    chmod +x ${JRS_HOME}/buildomatic/bin/*.sh && \
    chmod +x ${JRS_HOME}/apache-ant/bin/* && \
    wget "https://jdbc.postgresql.org/download/postgresql-${POSTGRES_JDBC_DRIVER_VERSION}.jar" \
        -P ${JRS_HOME}/buildomatic/conf_source/db/postgresql/jdbc --no-verbose

ENTRYPOINT ["/entrypoint-cmdline-ce.sh"]

CMD ["init"]
